CREATE TABLE concedentes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo_instituicao VARCHAR(50) NOT NULL,
    rede VARCHAR(50),
    razao_social VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL,
    telefone_institucional VARCHAR(20),
    especificacao_atividade TEXT,
    email_institucional VARCHAR(255),
    nome_representante VARCHAR(255),
    email_representante VARCHAR(255),
    cpf_representante VARCHAR(14),
    rg_representante VARCHAR(20),
    nome_supervisor VARCHAR(255),
    email_supervisor VARCHAR(255),
    celular_supervisor VARCHAR(20),
    whats_do_supervisor VARCHAR(20),
    endereco VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(255),
    cep VARCHAR(10),
    bairro VARCHAR(100),
    municipio VARCHAR(100),
    observacoes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 